apiVersion: v1
kind: Namespace
metadata:
  name: lingualive
  labels:
    name: lingualive

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lingualive-config
  namespace: lingualive
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/lingualive"
  REDIS_URL: "redis://redis-service:6379/0"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8000"

---
apiVersion: v1
kind: Secret
metadata:
  name: lingualive-secrets
  namespace: lingualive
type: Opaque
data:
  # Base64 encoded secrets
  sentry-dsn: <base64-encoded-sentry-dsn>
  google-credentials: <base64-encoded-google-credentials>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: lingualive
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lingualive-backend
  template:
    metadata:
      labels:
        app: lingualive-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/goutham-m7/verbaflow-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: lingualive-config
              key: MONGODB_URI
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: lingualive-config
              key: REDIS_URL
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: lingualive-secrets
              key: sentry-dsn
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/app/credentials/google-credentials.json"
        volumeMounts:
        - name: google-credentials
          mountPath: /app/credentials
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: google-credentials
        secret:
          secretName: lingualive-secrets
          items:
          - key: google-credentials
            path: google-credentials.json

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: lingualive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lingualive-frontend
  template:
    metadata:
      labels:
        app: lingualive-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/goutham-m7/verbaflow-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "https://api.lingualive.com"
        - name: REACT_APP_WS_URL
          value: "wss://api.lingualive.com"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: lingualive
spec:
  selector:
    app: lingualive-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: lingualive
spec:
  selector:
    app: lingualive-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lingualive-ingress
  namespace: lingualive
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - api.lingualive.com
    - www.lingualive.com
    secretName: lingualive-tls
  rules:
  - host: api.lingualive.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
  - host: www.lingualive.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: lingualive
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 